version: '2'

services:
  ftpd_server_1:
    image: stilliard/pure-ftpd:hardened
    container_name: ftpd_1
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: 
      - "./home:/home/guest/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: guest
      FTP_USER_PASS: 12345
      FTP_USER_HOME: /home/guest
    restart: always