version: "3"
services:
  daemon:
    build:
      context: ./src/
      dockerfile: daemon/Dockerfile
    ports:
      - "8081:8081"
  processor:
    build:
      context: ./src/
      dockerfile: processor/Dockerfile
  persistor:
    build:
      context: ./src/
      dockerfile: persistor/Dockerfile
  status:
    build:
      context: ./src/
      dockerfile: status/Dockerfile
