version: "3"
services:
  processor:
    container_name: processor
    build:
      context: ./src/
      dockerfile: processor/Dockerfile
  persistor:
    container_name: persistor
    build:
      context: ./src/
      dockerfile: persistor/Dockerfile
  status:
    container_name: status
    build:
      context: ./src/
      dockerfile: status/Dockerfile
  daemon:
    container_name: daemon
    build:
      context: ./src/
      dockerfile: daemon/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
       - status
  ftpserver:
    container_name: ftpserver
    build:
      context: ./src/alpine_ftp
      dockerfile: Dockerfile
    expose:
      - 21
    volumes:
      - ${PWD}/src/alpine_ftp/ftpfolder:/home/user1
    environment:
      - NAME=user1
      - PASS=Lalala123456
      - FOLDER=/home/user1
